spring:
  application:
    name: agent-test-camp
  ai:
    openai:
      api-key: ${MODEL_API_KEY}
      chat:
        options:
          model: ${CHAT_MODEL_NAME}
      image:
        options:
          size: 256x256
          model: ${IMAGE_MODEL_NAME}