spring:
  autoconfigure:
    exclude:
      - com.zaxxer.hikari.pool.HikariDataSource
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  application:
    name: agent-test-camp
  ai:
    openai:
      api-key: ${MODEL_API_KEY}
      chat:
        options:
          model: ${CHAT_MODEL_NAME}
      image:
        options:
          model: ${IMAGE_MODEL_NAME}
      audio:
        transcription:
          model: ${TRANSCRIPTION_MODEL_NAME}
          response-format: json
          temperature: 0.2
        speech:
          options:
            model: ${SPEECH_MODEL_NAME}
            voice: alloy
            response-format: wav
            speed: 1
project:
  properties:
    images:
      allowed-sizes: ${IMAGE_ALLOWED_SIZES}
      uniform-size: ${IMAGE_SIZE_UNIFORM}
      allowed-qualities: ${IMAGE_ALLOWED_QUALITIES}
      allowed-styles: ${IMAGE_ALLOWED_STYLES}